export const MENU_SUMMARY = `
APPETIZERS:
  - Guacamole Dip $5.99 | Fresh mashed avocado with a hint of lime and cilantro.
  - Guacamole de la Casa $8.75 | House-style guacamole with tomatoes, onions, and jalapeño.
  - Cheese Dip $5.99 | Creamy melted white cheese dip, a Fabian's classic.
  - Bean Dip $7.25 | Smooth refried beans topped with melted cheese.
  - Hamburger with Fries $10.25 | Juicy beef burger served with crispy golden French fries.
  - Chicken Fingers with Fries $10.25 | Crispy golden chicken tenders served with French fries.
  - Tortilla Chips $2.99 | House-made tortilla chips, light and perfectly salted.
  - Queso Fundido $6.50 | Melted cheese blended with Mexican sausage.
  - Borracho Beans $8.25 | Bean stew with bacon.
  - Cheese Dip with Rice $7.25 | Creamy cheese dip served alongside seasoned Mexican rice.
  - Chicken Wings $14.99 | 8 pcs. with buffalo sauce on top. Served with French fries.

NACHOS:
  - Nachos - Cheese $7.99 | Crispy tortilla chips smothered in our creamy house cheese d...
  - Nachos - Bean $6.99 | Tortilla chips loaded with seasoned refried beans.
  - Nachos - Ground Beef $10.75 | Chips topped with seasoned ground beef and melted cheese.
  - Nachos - Shredded Chicken $10.75 | Crispy chips piled high with tender shredded chicken and che...
  - Nachos Jalisco $17.99 | Chicken, beef, six shrimp and Mexican sausage. Served with o...
  - Nachos Supreme $14.99 | Cheese nachos with assorted topping of ground beef, chicken,...
  - Nachos Vallarta $17.99 | Polish sausage, grilled chicken, and grilled beef. Nacho chi...
  - Fajita Nachos $14.99 | Fajita-style chicken or beef with onions, tomatoes, and bell...
  - Shrimp Nachos $15.99 | Topped with onions, tomatoes, and bell peppers.
  - Nachos Texanos $17.99 | Shrimp, beef, and chicken, cooked with peppers, tomatoes, an...
  - Nachos San Luis $17.99 | Beef, chicken, shrimp, and Polish sausage.
  - Nachos de Carnitas $15.99 | Cheese dip, chips, and carnitas (tender chunks of pork).
  - Nachos al Carbón $15.99 | Steak or grilled chicken with flour chips. Served with beans...
  - Nachos Polish Sausage $12.99 | Polish sausage and cheese dip.
  - Nachos El Rey $12.99 | Ground beef, shredded chicken, beans, and cheese dip on top.
  - Jim's Nachos $11.99 | Steak or grilled chicken with your choice of rice or tortill...

SALADS:
  - Grilled Chicken Salad $12.99 | A bed of fresh lettuce, onions, bell peppers, and tomatoes t...
  - Taco Salad $11.25 | A crispy flour tortilla filled with shredded chicken or grou...
  - Taco Salad Fajita $13.99 | Fajita-style steak or chicken in a tortilla bowl cooked with...
  - Taco Salad Texano $15.99 | Steak, shrimp, and chicken, cooked with onions, bell peppers...
  - Guacamole Salad $5.99 | Fresh guacamole served on a bed of crisp lettuce.
  - Tossed Salad $5.99 | Lettuce, tomatoes, bell peppers, onions, and cheese.

FAJITAS:
  - Fajitas $15.99 | Chicken or steak.
  - Fajitas Mixtas $16.99 | Chicken and steak.
  - Fajitas Locas $19.89 | Steak, chicken, shrimp, and sausage.
  - Fajitas Texanas $19.89 | Marinated shrimp, steak, and chicken.
  - Shrimp Fajitas $19.89 | Marinated shrimp with sautéed bell peppers and onions. Serve...
  - Fajitas Del Mar $20.99 | Tilapia fish and shrimp with broccoli, carrots, and cauliflo...
  - Pineapple Fajitas $18.99 | Your choice of chicken or beef. Served with rice, beans, pic...
  - Especial San José $24.99 | Chicken, shrimp, grilled steak, ribs, and Polish sausage. Se...
  - Fajita San Luis $20.99 | Steak, chicken, shrimp, and Polish sausage, cooked with pepp...
  - Fajita De Carnitas $18.99 | Pork cooked with peppers, onions, and tomatoes. Served with ...
  - Fajita San Pancho $24.99 | Grilled chicken breast, a piece of carne asada, tilapia fish...
  - Molcajete Volcan $24.99 | Chicken breast, grilled steak, Mexican sausage, shrimp, gril...

STEAKS:
  - Steak Corral $21.99 | T-bone steak, two eggs, and borracho beans. Served with hash...
  - Steak Vallarta $24.99 | T-bone steak, shrimp, two eggs, and borracho beans. Served w...
  - Steak Ranchero $18.99 | T-bone steak with ranchero sauce on top. Served with rice, b...
  - Steak La Tampiqueña $21.99 | T-bone steak topped with grilled onions, served with rice, b...
  - Steak Azteca $24.99 | T-bone steak and eight shrimp with vegetables. Served with r...
  - Carne Asada $17.99 | Tender sliced steak served with rice, beans, lettuce, guacam...
  - Chile Colorado $17.99 | Chunks of steak cooked with red spicy sauce. Served with ric...
  - Tacos De Carne Asada $16.99 | Three soft tacos filled with steak, served with rice, beans,...
  - Efrain Special $21.99 | T-bone steak, French fries, broccoli, cauliflower, carrots, ...
  - Milanesa de Carne $21.99 | Breaded steak served with French fries, jalapeños, lettuce, ...
  - Caldo de Res $21.99 | Hearty Mexican beef soup with vegetables and rich broth.

CHICKEN:
  - La Carreta $18.99 | A grilled chicken breast, two eggs, and borracho beans. Serv...
  - Pollo Loco $16.99 | Seasoned grilled chicken breast topped with cheese sauce. Se...
  - Chilaquiles Mexicanos $16.99 | Tortilla chips covered with your choice of grilled chicken, ...
  - California $16.99 | Grilled chicken strips with cheese dip on top. Served with r...
  - Gringa $15.99 | A bed of rice topped with strips of grilled chicken or steak...
  - Gringa Texana $18.99 | Shrimp, steak, and chicken. Served with rice and cheese dip.
  - Pollo Azteca $21.99 | Grilled chicken topped with mushrooms, onions, and cheese sa...
  - Chicken Delight $17.99 | Steamed broccoli, cauliflower, and carrots, topped in our cr...
  - Pollo Acapulco $17.99 | A grilled chicken breast topped with chorizo and cheese sauc...
  - Chicken Soup $12.25 | Warm and comforting Mexican-style chicken soup.
  - Pollo Feliz $16.99 | Grilled chicken breast. Served with lettuce, sour cream, pic...
  - Pollo A La Mexicana $18.99 | Grilled chicken breast with sautéed onions, bell peppers, an...
  - Milanesa de Pollo $21.99 | Breaded chicken breast served with French fries, jalapeño, l...

PORK:
  - Carnitas $16.99 | Seasoned tender pork tips served with Mexican rice, beans, j...
  - Traditional Ribs $12.99 | Served with your choice of Mexican rice or French fries and ...
  - Chile Verde $16.99 | Pork chunks with green sauce, served with rice, beans, and t...

DEL MAR (SEAFOOD):
  - Shrimp Brochette $21.99 | Eight jumbo shrimp wrapped in bacon and filled with jalapeño...
  - Camarones al Mojo de Ajo $18.99 | Shrimp with exquisite Mexican garlic sauce. Served with rice...
  - Shrimp Tacos $16.99 | Three grilled shrimp tacos with lettuce, shredded cheese, an...
  - Camarones Rancheros $18.99 | Grilled shrimp covered in ranchero sauce. Served with rice, ...
  - Shrimp Delight $18.99 | Grilled shrimp with steamed broccoli, cauliflower, and carro...
  - Camarones a la Diabla $16.99 | Grilled shrimp with delicious Mexican hot sauce. Served with...
  - Fish & Shrimp $18.99 | Grilled tilapia fillet and shrimp served with rice, broccoli...
  - El Rey Shrimp $16.99 | Grilled shrimp with onions in cheese sauce, served over a be...
  - Fish Tacos $16.99 | Three grilled tilapia fish tacos with lettuce, shredded chee...
  - Shrimp Cocktail $15.99 | Chilled shrimp in a tangy tomato cocktail sauce with avocado...
  - Mojarra $17.99 | Served with rice, lettuce, pico de gallo, and sliced avocado...
  - Chago Special $17.99 | Two breaded tilapia, served with French fries, lettuce, jala...
  - Mojarra Feliz $21.99 | Six shrimp, rice, lettuce, avocado, pico de gallo, jalapeño,...
  - Caldo de Mariscos $23.99 | Rich and spicy Mexican seafood broth with shrimp and fish.

BURRITOS:
  - Burrito Acapulco $15.99 | Flour tortilla stuffed with shredded pork, cooked with tomat...
  - Burrito Deluxe $13.99 | Two burritos: One shredded chicken and one ground beef, topp...
  - Burrito San Luis $18.99 | A big flour tortilla filled with beef, chicken, shrimp, Poli...
  - Burritos Mexicanos $13.99 | Two burritos filled with ground beef and topped with cheese ...
  - Burrito Supreme $15.99 | Extra big burrito filled with tender slices of steak or chic...
  - Burrito Texano $17.99 | Steak, chicken, and shrimp, cooked with peppers, onions, and...
  - Burrito Special $8.99 | One burrito filled with ground beef topped with lettuce, tom...
  - Burrito Fajita Shrimp $16.99 | Cooked with peppers, onions, and tomatoes, with cheese dip o...
  - Hot and Spicy Burrito $13.99 | Flour tortilla filled with rice, beans, ground beef, chicken...
  - Burrito Fajita $15.99 | Steak or chicken, cooked with bell peppers, onions, and toma...
  - Burrito Real $13.99 | Large burrito with your choice of ground beef or shredded ch...

ENCHILADAS:
  - Enchiladas Supremas $13.99 | Four enchiladas: chicken, beef, cheese, and beans. Topped wi...
  - Enchiladas Yolanda $13.99 | Three chicken enchiladas. Served with rice and salad.
  - Enchiladas Rancheras $13.99 | Four chicken enchiladas topped with mole ranchero sauce, let...
  - Enchiladas Suizas $13.99 | Three cheese enchiladas topped with pork cooked with onions,...
  - Enchiladas Patrón $16.99 | Three enchiladas steak, grilled chicken or shrimp. Served wi...
  - Enchiladas Tapatias $14.99 | Three enchiladas stuffed with spinach and mushrooms. Served ...

QUESADILLA DINNERS:
  - Quesadilla Rellena $12.25 | A flour tortilla grilled and stuffed with shredded cheese, c...
  - Quesadilla Deluxe $12.25 | A flour tortilla stuffed with shredded cheese and chicken. S...
  - Shrimp Quesadilla $17.99 | Shrimp cooked with onions, tomatoes, bell peppers, and shred...
  - Quesadilla Fajita $15.99 | Fajita-style beef or chicken cooked with onions, bell pepper...
  - Quesadilla San Luis $17.99 | A big flour tortilla stuffed cooked with grilled chicken, st...
  - Quesadilla Texana $17.99 | Steak, chicken, and shrimp, cooked with peppers, onions, tom...
  - Quesa Birrias $16.99 | Three quesabirrias served with rice, beans, onion, cilatro, ...

HOUSE SPECIALS:
  - Guadalajara Special $21.99 | Tender sliced steak, six shrimp, two taquitos Mexicanos, and...
  - Sincronizada $14.99 | Our favorite grilled tortilla sandwich stuffed with beef or ...
  - Veracruz $15.99 | Six shrimp, two shredded chicken enchiladas with green sauce...
  - Sonora $15.99 | Two cheese enchiladas topped with green sauce, one poblano p...
  - Huevos con Chorizo $13.99 | Two eggs with Mexican sausage, rice, and tortillas.
  - Huevos Rancheros $12.99 | Two eggs topped with ranchero sauce. Served with rice, beans...
  - Chimichanga $12.99 | Flour tortilla filled with beef tips or shredded chicken, th...
  - Chimichanga (Shrimp) $13.99 | Golden deep-fried flour tortilla stuffed with seasoned shrim...
  - Chimichanga Texana $14.99 | Chimichanga with shrimp, grilled chicken, and steak cooked w...
  - El Rey Special $21.99 | Six shrimp and a grilled chicken breast. Served with rice, b...
  - Taquitos Mexicanos $12.99 | Two beef and two chicken taquitos lightly deep fried. Served...
  - Torta Mexicana $13.99 | Your choice of chicken, steak, Mexican sausage or fried pork...
  - Fabian Special $21.99 | Eight shrimp, Polish sausage and French fries. Served with b...
  - Papa Loca $18.99 | Steak or chicken, served with rice, French fries, and cheese...
  - Los Cuates $24.99 | Steak, chicken, shrimp, and Polish sausage. Served with rice...
  - Flautas Mexicanas $15.99 | Four corn tortilla filled with your choice of shredded chick...
  - Gringa Texana $18.99 | Shrimp, steak, and chicken. Served with rice and cheese dip.

A LA CARTE:
  - Taco (Ground beef or shredded chicken) $2.50 | Classic soft taco with your choice of ground beef or shredde...
  - Taco Grilled Chicken $3.75 | Shredded cheese and lettuce.
  - Taco de Carne Asada $3.75 | Served with onions and cilantro.
  - Taco de Carnitas $3.75 | Served with onion and cilantro.
  - Taco de Chorizo $3.75 | Served with onion and cilantro.
  - Taco Al Pastor $3.75 | Served with onion and cilantro.
  - Shrimp Taco $4.99 | Served with lettuce, pico de gallo, and shredded cheese.
  - Fish Taco $4.99 | Served with lettuce, pico de gallo, and shredded cheese.
  - Taco Polish Sausage $2.99 | Soft taco filled with savory grilled Polish sausage.
  - Burrito (Ground beef or shredded chicken) $6.25 | Flour tortilla wrapped around seasoned ground beef or shredd...
  - Bean Burrito $4.99 | Red sauce on top.
  - Burrito (Steak, grilled chicken or shrimp) $7.99 | Red sauce on top.
  - Enchilada (Ground beef or shredded chicken) $3.25 | Red sauce on top.
  - Enchilada (Steak, grilled chicken or shrimp) $4.25 | Red sauce on top.
  - Cheese Enchilada $2.99 | Red sauce on top.
  - Beans Enchilada $1.99 | Red sauce on top.
  - Chile Relleno $5.25 | Roasted poblano pepper stuffed with cheese in egg batter.
  - Chimichanga (Ground beef or chicken) $6.99 | Cooked with peppers, onions, tomatoes, and cheese dip on top...
  - Chimichanga (Grilled chicken, steak or shrimp) $8.99 | Cheese dip on top.
  - Chimichanga Polish Sausage $6.25 | Cheese dip on top.
  - Tostada $5.50 | Ground beef, cheese dip, shredded cheese, lettuce, tomatoes,...
  - Tostada de Chorizo $5.99 | Lettuce, sour cream, tomatoes, and shredded cheese.
  - Tostada (Steak, grilled chicken or shrimp) $6.99 | Crispy tostada topped with your choice of steak, grilled chi...
  - Chalupa $3.99 | Beans, lettuce, guacamole, tomatoes, and shredded cheese.
  - Quesadilla (Shredded beef or chicken) $6.99 | Cooked with peppers, onions, and tomatoes, with shredded che...
  - Spinach Quesadilla $5.99 | Spinach and shredded cheese inside.
  - Quesadilla Grande (Shredded chicken or shredded beef) $8.99 | Large flour tortilla filled with shredded chicken or beef an...
  - Grilled Quesadilla (Grilled steak or chicken) $8.99 | With shredded cheese inside.
  - Quesadilla Grande (Steak or grilled chicken) $11.25 | With shredded cheese inside.
  - Cheese Quesadilla $3.99 | Flour tortilla filled with melted cheese, crispy and golden.
  - Order Grilled Shrimp (15) $12.99 | Fifteen juicy grilled shrimp seasoned with our special Mexic...
  - Tamale $4.25 | Traditional corn masa tamale filled with seasoned meat.
  - Order Steak or Grilled Chicken $11.99 | Tender grilled steak or seasoned chicken breast, cooked to p...

SIDE ORDERS:
  - Mexican Rice $3.50 | Fluffy seasoned rice cooked with tomatoes and spices.
  - Refried Beans $3.50 | Smooth and creamy traditional Mexican refried pinto beans.
  - French Fries $4.25 | Golden crispy French fries, perfectly salted.
  - Hash Brown $4.25 | Crispy shredded potato patty, golden on the outside.
  - Shredded Cheese $2.25 | Freshly shredded Mexican blend cheese.
  - Chiles Toreados $3.99 | Charred whole jalapeños with onions, a spicy Mexican classic...
  - Tomatillo Sauce $2.99 | Tangy green tomatillo sauce with a smoky kick.
  - Pico de Gallo $1.99 | Fresh diced tomatoes, onions, cilantro, and jalapeño.
  - California Vegetables $5.99 | Steamed broccoli, cauliflower, and carrots, lightly seasoned...
  - Bell Peppers $1.99 | Freshly sliced colorful bell peppers.
  - Grilled Onions $1.99 | Sweet caramelized onions grilled to golden perfection.
  - Tortillas (3) $1.35 | Three warm soft flour or corn tortillas.
  - Small Sour Cream $1.99 | Cool and creamy sour cream on the side.
  - Tomatoes $0.99 | Fresh sliced ripe tomatoes.
  - Jalapeños $1.99 | Fresh or pickled jalapeño peppers for extra heat.
  - Cilantro $0.99 | Fresh fragrant cilantro leaves.
  - Onions $0.99 | Fresh diced or sliced white onions.
  - Lettuce $0.99 | Crisp shredded lettuce.
  - Sliced Avocado (1) $3.99 | One perfectly ripe sliced avocado.
  - Large Sauce To-Go $3.99 | A large container of our house red sauce to take home.
  - Mushrooms $4.99 | Sautéed seasoned mushrooms, rich and savory.
  - Chorizo $6.99 | Spicy Mexican pork sausage, bold and flavorful.
  - Polish Sausage $6.99 | Smoky grilled Polish sausage with rich savory flavor.

BUILD YOUR OWN VEGETARIAN:
  - Veggie Burrito $12.25 | Large burrito filled with onions, bell peppers, carrots, bro...
  - Veggie Quesadilla $12.25 | A flour tortilla grilled and stuffed with onions, bell peppe...
  - Vegetarian Fajitas $13.99 | Sautéed onions, bell peppers, carrots, broccoli, cauliflower...

KID'S MENU:
  - One burrito and one taco. | A classic kid's combo: one soft burrito and one taco.
  - One beef taco, rice, and beans. | A hearty kid's plate with a beef taco, rice, and beans.
  - One quesadilla and one enchilada. | Cheesy quesadilla paired with a saucy enchilada.
  - Mini taco salad. | A fun mini taco salad bowl, perfect for little ones.
  - One burrito, rice, and beans. | A filling kid's plate with a burrito, rice, and beans.
  - Enchilada, rice, and beans. | A saucy enchilada with rice and creamy refried beans.
  - Cheese quesadilla, rice, and beans. | Melty cheese quesadilla served with rice and beans.
  - Cheese quesadilla with French fries. | Golden cheese quesadilla served with crispy French fries.
  - Chicken fingers with French fries. | Crispy chicken tenders with golden French fries.
  - Cheeseburger with French fries. | Juicy cheeseburger with melted cheese and French fries.
  - Chicken nuggets with French fries. | Tender chicken nuggets with crispy French fries.
  - Cheese sticks with French Fries. | Golden fried cheese sticks with crispy French fries.
  - Shredded chicken or ground beef nachos. | Cheesy nachos topped with shredded chicken or ground beef.
  - Grilled chicken, steak or six shrimp with rice and cheese dip. $10.99 | Grilled chicken, steak, or six shrimp with rice and cheese d...

LUNCH:
  - Lunch Special No. 1 $11.25 | One chile relleno, one taco, beans, and guacamole salad.
  - Lunch Special No. 2 $11.25 | One burrito, rice, and beans.
  - Lunch Special No. 3 $11.25 | One burrito, one taco, and rice.
  - Lunch Special No. 4 $11.25 | Chile relleno, rice, and beans.
  - Lunch Special No. 5 $11.25 | One enchilada, rice, and beans.
  - Lunch Special No. 6 $11.25 | One cheese enchilada, one burrito, and guacamole salad.
  - Lunch Special No. 7 $11.25 | Two chicken enchiladas topped with enchilada sauce. Served w...
  - Lunch Special No. 8 $11.25 | One tamale, rice, and beans.
  - Lunch Special No. 9 $11.25 | One taco, rice, and beans.
  - Lunch Special No. 10 $11.25 | One chicken quesadilla, rice, and beans.
  - Lunch Fajitas $12.99 | Steak or chicken fajita with bell peppers and onions. Served...
  - El Rey Burrito $12.99 | Burrito filled with tender sliced chicken or beef, bell pepp...
  - Sincronizada $12.99 | Our favorite grilled tortilla sandwich stuffed with beef or ...
  - Pollo Loco $12.99 | Grilled chicken breast with cheese dip on top, served with r...
  - Quesadilla Deluxe $11.25 | A flour tortilla with cheese and chicken. Served with lettuc...
  - Huevos Rancheros $11.25 | Two ranch-style eggs topped with ranchero sauce. Served with...
  - Huevos con Chorizo $12.25 | Two eggs with Mexican sausage, rice, and tortillas.
  - Speedy Gonzalez $11.25 | One taco and one enchilada. Served with rice and beans.
  - Milanesa de Pollo $21.99 | Breaded chicken breast served with French fries, jalapeño, l...
  - California (Lunch) $14.99 | Grilled chicken strips with cheese dip on top. Served with r...
  - Veracruz (Lunch) $15.99 | Six shrimp, two shredded chicken enchiladas with green sauce...
  - Chicken Soup (Lunch) $12.99 | Warm Mexican-style chicken soup, comforting and flavorful.
  - Fajita Taco Salad (Lunch) $12.99 | Fajita-style chicken or steak with grilled onions and bell p...
  - Fajita Quesadilla (Lunch) $12.99 | Fajita-style beef or chicken cooked with onions, bell pepper...
  - Burrito Special (Lunch) $8.99 | One burrito filled with your choice of ground beef or shredd...
  - Chimichanga (Lunch) $11.99 | A flour tortilla filled with shredded chicken or beef, then ...
  - Taco Salad (Lunch) $11.25 | Ground beef or shredded chicken, cheese dip, lettuce, tomato...
  - Enchilada Supreme (Lunch) $11.25 | One beef and one chicken enchilada topped with lettuce, guac...
  - Taquitos Mexicanos (Lunch) $11.25 | Two taquitos, one beef and one chicken. Served with lettuce,...
  - Torta Mexicana (Lunch) $13.99 | Your choice of chicken, steak, Mexican sausage or fried pork...
  - Flautas Mexicanas (Lunch) $11.25 | Two corn tortilla filled with your choice of shredded chicke...

DESSERTS:
  - Mexican Flan $6.25 | Traditional Mexico City-style crème caramel. Baked fresh dai...
  - Fried Ice Cream $6.25 | Delicious rich vanilla ice cream, rolled in crispy flakes, t...
  - Sopapilla $5.25 | A flour tortilla deep-fried to a golden brown, topped with h...
  - Sopapilla with Ice Cream $6.25 | Golden fried sopapilla topped with a scoop of vanilla ice cr...

SOFT DRINKS:
  - Coke, Diet Coke, Zero Coke, Sprite, Fanta, Dr Pepper, Lemonade $3.29 | Your choice of refreshing fountain drinks with free refills.
  - Sweet or Unsweet Tea $3.29 | Classic Southern-style sweet or unsweet iced tea with free r...
  - Jarritos $3.75 | No refills.
  - Coffee $3.29 | Rich hot coffee, perfect to finish your meal.
  - Milk $3.50 | No refills.
  - Roy Rogers $3.99 | Ginger ale with grenadine and a maraschino cherry.
  - Shirley Temple $3.99 | Sprite with grenadine and a maraschino cherry, kids' favorit...
  - Agua de Horchata y Jamaica $4.99 | Traditional Mexican rice water or hibiscus flower agua fresc...

DAIQUIRIS:
  - Daiquiri (Peach, Strawberry or Piña Colada) $6.25 | Frozen blended daiquiri in peach, strawberry, or piña colada...

MARGARITAS:
  - Lime Margaritas $6.75+ | Frozen or on the rocks.
  - Flavored Margaritas $7.75+ | Frozen or on the rocks. Mango, strawberry, watermelon, and p...
  - Texas Margaritas $10.99+ | Bold on-the-rocks margaritas with premium tequila, Texas-siz...

COLD BEERS:
  - Bud Light (Draft) $3.25+ | Ice-cold Bud Light on draft, light and refreshing.
  - Dos Equis XX (Draft) $2.99+ | Smooth and crisp Dos Equis XX lager on draft.
  - Domestic Beers (Bud Light, Budweiser, Miller Lite, Michelob Light) $4.25 | Your choice of classic American domestic beers, ice cold.
  - Imported Beers (Corona, Tecate, Dos Equis XX, Negra Modelo, Pacífico) $5.89 | Premium imported Mexican and international beers served ice ...
  - Micheladas $8.99 | Mexican beer mixed with lime juice, hot sauce, and spices.

MIXED DRINKS:
  - Amaretto Sour $7.99 | Sweet amaretto shaken with sour mix for a smooth cocktail.
  - Bloody Mary $7.99 | Bold tomato juice cocktail with vodka and spicy seasonings.
  - Bourbon and Coke $7.99 | Smooth bourbon whiskey paired with ice-cold Coca-Cola.
  - Cuba Libre $7.99 | Classic rum and Coke with a squeeze of fresh lime.
  - Tequila Shot (Patron, Don Julio) $8.99 | Premium tequila shot from Patron or Don Julio, smooth and cl...
  - Long Island Iced Tea $7.99 | A powerful blend of five spirits with a splash of cola.
  - Screw Driver $7.99 | Crisp vodka mixed with fresh orange juice.
  - Tequila Sunrise $7.99 | Tequila with orange juice and grenadine for a stunning sunri...
  - White Russian $7.99 | Smooth vodka, coffee liqueur, and cream over ice.
  - House Shot Tequila (Jose Cuervo, 1800, Jack Daniel's, Crown Royal) $7.99 | Your choice of house spirits: Cuervo, 1800, Jack Daniel's, o...

WINES:
  - Glass $5.25 | A glass of your choice: Sangría, Burgundy, Zinfandel, or Mer...
  - Carafe $14.99 | A full carafe of house wine: Sangría, Burgundy, Zinfandel, o...
  - ½ Carafe $8.75 | A half carafe of your favorite house wine selection.
  - Wine-A-Rita $12.99 | A unique blend of wine and margarita — the best of both worl...`;
